[package]
authors = ["The Rust Project Developers"]
name = "rustc_hair"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustc_hair"
path = "lib.rs"
doctest = false

[dependencies]
log = "0.4"
smallvec = { version = "=1.5.1", features = ["union", "may_dangle"] }
